### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by AshiePleb** [dylanhansch/CloudFlare-subdomain#4]
Will this ever be updated?

**Comment by dylanhansch** [comment]
I likely won't be able to contribute any updates, since I'm too busy now. Thanks for your interest though!

If you're interested in contributing, most of this code will still work. You'll just need to swap out the 3rd party v1 API conduit for Cloudflare's PHP SDK: https://github.com/cloudflare/cloudflare-php . Then tweak a few things in the code.
